---
title: "Getting Started with R: Session 4"
author: "S. Kelly | Scholar Support and Data Services | Fall 2025"
format: 
  revealjs: 
    code-overflow: wrap
    footer: "S.Kelly | Getting Started with R | Fall 2025"
editor: visual
execute: 
  echo: true
---

## Open your R project, create a .R file, & load R packages

```{r}
library(tidyverse)
library(cherryblossom)

# run search to confirm loaded packages
search()
```

# Working with Rows

## Logical Comparisons & Boolean Operators in R

```{r}
#| echo: TRUE
#| eval: FALSE
== # is equal to
!= # is not equal to
>= # greater than or equal to
<= # less than or equal to
is.na # is missing
!is.na # is not missing
```

<br>

```{r}
#| echo: TRUE
#| eval: FALSE
& # AND
| # OR
! # NOT
```

## Review these comparisons

```{r}
"red" == "blue"
"red" == "red"
-11 > 10
7 == 5|7
```

## filter

```{r}
run17 |> 
  filter(event == "5K") |> 
  head(10)
```

## Let's filter even more...

```{r}
run17 |> 
  filter(event == "5K" & sex == "M") |> 
  head(10)
```

## Activity

Filter the run17 dataset to only men over 40 who ran the 10 mile race

```{r}
#| echo: TRUE
#| eval: FALSE
run17 |> 
  filter(? == ? & ? >= ? & ? == ?)
```

## Activity Check

```{r}
run17 |> 
  filter(event == "10 Mile" & age >= 40 & sex == "M")
```